import { readFileSync, writeFileSync } from 'node:fs';
import { runInNewContext } from 'node:vm';

const source = readFileSync('initialCut.html', 'utf8');
const config = source.match(/<script id="tailwind-config">([\s\S]*?)<\/script>/)?.[1];
const styles = source.match(/<style>([\s\S]*?)<\/style>/)?.[1];
if (!config || !styles) throw new Error('Could not find the approved Stitch theme.');
writeFileSync('tailwind.config.cjs', `${config.replace('tailwind.config = {', 'module.exports = {\n      content: ["./index.html", "./initialCut.html", "./src/**/*.{ts,tsx}"],')}\n`);
writeFileSync('src/app.css', `@tailwind base;\n@tailwind components;\n@tailwind utilities;\n${styles}\n\nhtml { scroll-behavior: smooth; }\n[id] { scroll-margin-top: 6rem; }\nbody, a, button, input, select, textarea { cursor: auto !important; }\na, button, input[type=range] { cursor: pointer !important; }\n#cursor-dot { display: none !important; }\n:focus-visible { outline: 2px solid #785837; outline-offset: 3px; }\nheader nav a.mk-nav-link { position: relative; border: 0; padding-bottom: .35rem; }\nheader nav a.mk-nav-link::after { content: ''; position: absolute; left: 0; right: 0; bottom: 0; height: 2px; background: #785837; transform: scaleX(0); transform-origin: left; transition: transform .32s cubic-bezier(.2,.8,.2,1); }\nheader nav a.mk-nav-link:hover::after, header nav a.mk-nav-link:focus-visible::after, header nav a.mk-nav-link.is-active::after { transform: scaleX(1); }\nheader nav a.mk-nav-link.is-active { color: #1b1c1a !important; }\n#hero img { opacity: 1 !important; filter: contrast(1.04) saturate(1.04); }\n#hero .bg-gradient-to-t { opacity: .5; }\n#hero .bg-radial { opacity: .18; }\n#projects img { opacity: 1 !important; filter: contrast(1.04) saturate(1.06); }\n.mk-stage-photo { animation: mk-photo-reveal .65s cubic-bezier(.2,.8,.2,1) both; }\n.mk-stage-panel > :last-child { animation: mk-content-reveal .55s cubic-bezier(.2,.8,.2,1) both; }\n.mk-stage-tab { position: relative; overflow: hidden; }\n.mk-stage-tab::after { content: ''; position: absolute; left: 0; bottom: 0; height: 2px; width: 100%; background: #a47b4d; transform: scaleX(0); transform-origin: left; transition: transform .4s cubic-bezier(.2,.8,.2,1); }\n.mk-stage-tab:hover::after, .mk-stage-tab[aria-pressed=true]::after { transform: scaleX(1); }\n.mk-three-study { position: absolute; top: 1.5rem; right: 1.5rem; z-index: 12; width: min(38%, 230px); aspect-ratio: 1; border: 1px solid rgba(255,220,189,.45); background: rgba(12,17,20,.64); box-shadow: 0 12px 44px rgba(0,0,0,.26), inset 0 0 0 1px rgba(255,255,255,.06); backdrop-filter: blur(6px); pointer-events: none; }\n.mk-three-study::after { content: 'MK / SPATIAL STUDY'; position: absolute; left: .8rem; bottom: .7rem; color: #e9bf97; font: 9px 'JetBrains Mono', monospace; letter-spacing: .12em; }\n@keyframes mk-photo-reveal { from { clip-path: inset(0 100% 0 0); transform: scale(1.04); opacity: .5; } to { clip-path: inset(0 0 0 0); transform: scale(1); opacity: 1; } }\n@keyframes mk-content-reveal { from { transform: translateY(18px); opacity: 0; } to { transform: translateY(0); opacity: 1; } }\n@media (prefers-reduced-motion: reduce) { html { scroll-behavior: auto; } *, *::before, *::after { animation-duration: .01ms !important; transition-duration: .01ms !important; } }\n`);
const stagesExpression = source.match(/const ecosystemStages = (\[[\s\S]*?\]);/)?.[1];
if (!stagesExpression) throw new Error('Could not find the ecosystem content.');
writeFileSync('src/ui/screens/HomeScreen/ecosystemStages.json', JSON.stringify(runInNewContext(stagesExpression), null, 2));
